// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "s3.endpoint": string;
      "s3.region": string;
      "s3.accessKeyId": string;
      "s3.secretAccessKey": string;
      "s3.bucketName": string;
      "s3.prefix": string;
      "sync.autoSync": boolean;
      "sync.syncInterval": number;
      "conflictResolution": string;
      "sync.incremental": boolean;
      "sync.incrementalMaxDays": number;
    };
  }
}
